language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode11
      script:
        - cmake --version
        - mkdir ./build_pure_17_release
        - cd ./build_pure_17_release
        - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=Release -DGLM_TEST_ENABLE=ON -DGLM_TEST_ENABLE_CXX_17=ON -DGLM_TEST_FORCE_PURE=ON ..
        - cmake -E time cmake --build .
        - ctest
      env:
        - MATRIX_EVAL="INFO=C++17-pure-release"

    - os: osx
      osx_image: xcode11
      script:
        - cmake --version
        - mkdir ./build_pure_17_debug
        - cd ./build_pure_17_debug
        - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=Debug -DGLM_TEST_ENABLE=ON -DGLM_TEST_ENABLE_CXX_17=ON -DGLM_TEST_FORCE_PURE=ON ..
        - cmake -E time cmake --build .
        - ctest
      env:
        - MATRIX_EVAL="INFO=C++17-pure-debug"

    - os: osx
      osx_image: xcode11
      script:
        - cmake --version
        - mkdir ./build_avx_17_release
        - cd ./build_avx_17_release
        - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=Release -DGLM_TEST_ENABLE=ON -DGLM_TEST_ENABLE_CXX_17=ON -DGLM_TEST_ENABLE_LANG_EXTENSIONS=ON -DGLM_TEST_ENABLE_SIMD_AVX=ON ..
        - cmake -E time cmake --build .
        - ctest
      env:
        - MATRIX_EVAL="INFO=C++17-avx-release"

    - os: osx
      osx_image: xcode11
      script:
        - cmake --version
        - mkdir ./build_avx_17_debug
        - cd ./build_avx_17_debug
        - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=Debug -DGLM_TEST_ENABLE=ON -DGLM_TEST_ENABLE_CXX_17=ON -DGLM_TEST_ENABLE_LANG_EXTENSIONS=ON -DGLM_TEST_ENABLE_SIMD_AVX=ON ..
        - cmake -E time cmake --build .
        - ctest
      env:
        - MATRIX_EVAL="INFO=C++17-avx-debug"

    - os: android
      name: android
      language: android
      sudo: true
      android:
        components:
            - tools
            - platform-tools
            - extra-google-m2repository
            - extra-android-m2repository
      addons:
        apt_packages:
            - pandoc
        
      before_install:
        - sudo apt-get install ant

      install:
        - echo y | sdkmanager "ndk-bundle"
        - echo y | sdkmanager "cmake;3.10.2.4988404"
        - echo y | sdkmanager --channel=3 --channel=1 "cmake;3.10.2.4988404"
        - echo y | sdkmanager "lldb;3.1"
      
      before_script:
        - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle

      script:
        - cd ./android
        - chmod +x gradlew
        - ./gradlew build
        
before_install:
    - eval "${MATRIX_EVAL}"


